apiVersion: apps/v1
kind: Deployment
metadata:
  name: protocol-server
spec:
  selector:
    matchLabels:
      app: protocol-server
  template:
    metadata:
      labels:
        app: protocol-server
    spec:
      containers:
        - name: protocol-server
          image: felipes102/legishub-protocol
          ports:
            - containerPort: 8081